apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: demo-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3-alpine-slim
        ports:
        - containerPort: 80
